---
-   id: hadolint
    name: hadolint
    description: "A smarter Dockerfile linter that helps you build best practice Docker images"
    entry: hadolint
    language: python
    types: [dockerfile]
    require_serial: true
